services:
  db:
    container_name: todos-db
    image: postgres:latest
    restart: always
    ports:
      - '5492:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres