/* tslint:disable */


        /**
         * AUTO-GENERATED FILE - DO NOT EDIT!
         *
         * This file was automatically generated by schemats v.9.0.1
         *
         */

    
        export interface Accounts {
        createdAt:Date| null;
id:number;
name:string;
updatedAt:Date| null;

        }
    
        export interface Comments {
        createdAt:Date| null;
id:number;
taskId:number;
text:string;
updatedAt:Date| null;

        }
    
        export interface Migrations {
        id:number;
name:string;
runOn:Date;

        }
    
        export interface ProjectMembers {
        createdAt:Date| null;
id:number;
projectId:number;
updatedAt:Date| null;
userId:number;

        }
    
        export interface Projects {
        accountId:number;
createdAt:Date| null;
description:string| null;
id:number;
name:string| null;
updatedAt:Date| null;

        }
    
        export interface Tasks {
        createdAt:Date| null;
description:string| null;
id:number;
name:string| null;
position:number| null;
projectId:number;
tags:Array<string>| null;
updatedAt:Date| null;

        }
    
        export interface Users {
        accountId:number| null;
createdAt:Date| null;
email:string;
hash:string;
id:number;
name:string| null;
salt:string;
updatedAt:Date| null;

        }
    
export interface DBTables {
  accounts: Accounts
  comments: Comments
  migrations: Migrations
  projectMembers: ProjectMembers
  projects: Projects
  tasks: Tasks
  users: Users
}
